framework:
    cache:
        pools:
            forecast_pool:
                default_lifetime: 60
                adapter: cache.adapter.redis
                provider: app.harvest_redis_provider

            harvest_pool:
                default_lifetime: 1800
                adapter: cache.adapter.redis
                provider: app.harvest_redis_provider

            slack_pool:
                default_lifetime: 120
                adapter: cache.adapter.redis
                provider: app.harvest_redis_provider
