security:
    providers:
        oauth:
            id: App\Security\UserProvider\OAuthUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|forecast|images|js)/
            security: false
        public:
            pattern: ^/(privacy-policy|terms-of-service)$
            security: false
        main:
            entry_point: App\Security\AuthenticationEntryPoint
            pattern: ^/
            logout:
                path: /logout
                target: /
            switch_user: true
            custom_authenticators:
                - App\Security\HarvestAuthenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }
        - { path: ^/forecast/, roles: PUBLIC_ACCESS }
        - { path: ^/slack, roles: PUBLIC_ACCESS }
        - { path: ^/_admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH]
