twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@dev:
    twig:
        strict_variables: true

when@test:
    twig:
        strict_variables: true
