version: '3.7'

volumes:
    mysql-data: {}
    redis-data: {}

services:
    router:
        build: services/router
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        network_mode: host

    frontend:
        build: services/frontend
        depends_on:
            - mysql
        volumes:
            - "../${PROJECT_DIRECTORY}:/home/app/application:cached"
        environment:
            - "PHP_VERSION=${PHP_VERSION}"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.rule=Host(${PROJECT_DOMAINS})"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}-frontend-unsecure.rule=Host(${PROJECT_DOMAINS})"
            # Comment the next line to be able to access frontend via HTTP instead of HTTPS
            - "traefik.http.routers.${PROJECT_NAME}-frontend-unsecure.middlewares=redirect-to-https@file"

    mysql:
        build: services/mysql
        volumes:
            - mysql-data:/var/lib/mysql

    encore:
        build: services/builder
        volumes:
            - "../${PROJECT_DIRECTORY}:/home/app/application:cached"
        command: "yarn run dev-server --host 0.0.0.0 --port 9999 --hot --public https://encore.${PROJECT_ROOT_DOMAIN}/ --disable-host-check"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-encore.rule=Host(`encore.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-encore.tls=true"
            - "traefik.http.services.encore.loadbalancer.server.port=9999"

    redis:
        image: redis:5
        volumes:
            - "redis-data:/data"
